name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-x64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-arm64:

    runs-on: ubuntu-latest-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-x86:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang C_FLAGS=-m32

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -m32 -shared -fPIC crt.o dll.c -o libdll.so
        clang -m32 main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-arm32:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang C_FLAGS=-m32

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -m32 -shared -fPIC crt.o dll.c -o libdll.so
        clang -m32 main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
