name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-x64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-arm64:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-x86:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install 32-bit libs
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install gcc-multilib g++-multilib libc6-dev-i386

    - name: Compile runtime
      run: make C_COMPILER=clang C_FLAGS=-m32

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -m32 -shared -fPIC crt.o dll.c -o libdll.so
        clang -m32 main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-linux-arm32:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Install 32-bit libs
      run: |
        sudo apt update
        sudo apt install clang lld gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Compile runtime
      run: make C_COMPILER=clang C_FLAGS="--target=armv7-linux-gnueabihf -fuse-ld=lld"

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang --target=armv7-linux-gnueabihf -fuse-ld=lld -shared -fPIC crt.o dll.c -o libdll.so
        clang --target=armv7-linux-gnueabihf -fuse-ld=lld main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-macos-x64:

    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4

    - name: Install binutils
      run: brew install binutils

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
      
  build-macos-arm64:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4

    - name: Install binutils
      run: brew install binutils

    - name: Compile runtime
      run: make C_COMPILER=clang

    - name: Compile tests
      run: |
        echo -e '#include <stdio.h>\nint main() {fprintf(stderr,"Executable works\\n");}\nvoid print() {fprintf(stderr,"Library works\\n");}' > dll.c
        echo -e 'extern void print();\nint main() {print();}' > main.c
        clang -shared -fPIC crt.o dll.c -o libdll.so
        clang main.c -L. -ldll

    - name: Test Executable
      run: ./libdll.so

    - name: Test Shared Object
      run: LD_LIBRARY_PATH=. ./a.out
